[package]
name = "ringfit-slack"
version = "0.1.0"
authors = ["Koji Ishimoto <koji.ishimoto@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.9.21"
scraper = "0.11.0"
