steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/ringfit-slack', '--build-arg', 'SLACK_WEBHOOK_URL=$_SLACK_WEBHOOK_URL', '.']
substitutions:
  _SLACK_WEBHOOK_URL: slack-url # default value
images: ['gcr.io/$PROJECT_ID/ringfit-slack']
