steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'ringfit-slack'
    args: ['build', '--tag=gcr.io/$PROJECT_ID/ringfit-slack', "--build-arg", "SLACK_WEBHOOK_URL=$SLACK_WEBHOOK_URL", '.']
    timeout: 2400s
  images: ['gcr.io/$PROJECT_ID/ringfit-slack']
