steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/ringfit-slack', '--build-arg', 'SLACK_WEBHOOK_URL=$_SLACK_WEBHOOK_URL', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/[ringfit-slack]:$COMMIT_SHA']
# Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'ringfit-slack'
  - '--image'
  - 'gcr.io/$PROJECT_ID/ringfit-slack:$COMMIT_SHA'
  - '--region'
  - 'asia-northeast2'
  - '--platform'
  - 'managed'
substitutions:
  _SLACK_WEBHOOK_URL: slack-url # default value
timeout: 2000s
images: ['gcr.io/$PROJECT_ID/ringfit-slack']
